### ISSUE TITLE
favourite file fixer

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#61]
Enormous bug in MainUI : if you add the same rom two times in favorite , your favorite file will be broken.

Source corrupted file : 
https://discord.com/channels/529983248114122762/891336865540620338/978804704870039613

---

Schmurtz describ the [steps to repair a file here](https://discord.com/channels/529983248114122762/931367023588569180/998035929627377764) : 

```
Well I've discovered some interesting things about the favourite bug : 
- as Toto said, there is all the data in the file (except the labels but that is easy to recover since it is the name of the rom without its extension)
- the file is corrupted either when you open the favorites but can also be corrupted when you launch a rom! (on the other hand it is not corrupted at the moment when you add a rom to the favorites)
- The corruption arrive when you have 2 identical labels in the list
- it's quite easy to provoke the corruption: you create a mario.zip on NES and a mario.zip on SNES, you add the 2 in favorites and it's broken: even if they are on different emulators it breaks favourites
- Therefore classically the users must have identical names of rom on different systems or we can also imagine mario.zip and mario.sfc in the same folder "SFC" and added both in favorites. 
- a workaround while waiting for a patch from mainUI would be to rename the labels by prefixing with the Emu and keeping the rom extension
- detail : the file must always end with an \n otherwise the next favorite added will not be displayed because it will be on the same line as the previous one 
- detail : the favourites list is not optimised in mainUI : each time you scroll down in the list, the full list is refreshed so the navigation is very slow when you have numerous items 



- Take the last line of the file (it contains all the data) 
- REPLACE all     ,"label"   with       }\n{"label"
- Rename labels with unique name from rom filename :  jq '.|=(.label=.rompath)'  favourite.json > newfav.json
- Then apply some little page layout...

If someone can compile jq for the miyoo mini I could make an app / script running directly on the Miyoo Mini to fix corrupted favourites.
```
---

low_k0 has compiled jq which allows to manage favorites easily  , [download here](https://dl.dropbox.com/s/w1nlvdnin2ih8ba/jq)

**Comment by schmurtzm** [comment]
Enormous bug in MainUI : if you add the same rom two times in favorite , your favorite file will be broken.

Schmurtz describ the [steps to repair a file here](https://discord.com/channels/529983248114122762/931367023588569180/998035929627377764)

low_k0 has compiled jq which allow to manage favorites easily"

**Comment by schmurtzm** [comment]
Seems fixed on the last Miyoo Mini+ firmware. Let's hope that the same fix will be applied for the Miyoo Mini on a future firmware 🤞

**Comment by filipmnowak** [comment]
> Seems fixed on the last Miyoo Mini+ firmware. Let's hope that the same fix will be applied for the Miyoo Mini on a future firmware crossed_fingers

not really: https://github.com/OnionUI/Onion/issues/280#issuecomment-1566008442

**Comment by schmurtzm** [comment]
On which beta version did you see that ?

**Comment by filipmnowak** [comment]
> On which beta version did you see that ?

mentioned in linked issue. it's `Onion V4.2.0.2-beta`.

**Comment by schmurtzm** [comment]
> mentioned in linked issue. it's `Onion V4.2.0.2-beta` / https://github.com/OnionUI/Onion/commit/4c7e2db

It should be fixed in the very last beta. But we have new problems with MainUI and some roms which are not showing.

**Comment by filipmnowak** [comment]
> > mentioned in linked issue. it's `Onion V4.2.0.2-beta` / [4c7e2db](https://github.com/OnionUI/Onion/commit/4c7e2db)
> 
> It should be fixed in the very last beta. But we have new problems with MainUI and some roms which are not showing.

i feel like issue or other, similar is still happening.
- i searched for a game via search app.
- found one with same name, added to favorite twice. (in default MAME and "expert" Final Burn).
- i didn't noted a change until reboot. all favorites (around 20) beside one game were gone.
... funnily enough, i sorted favorites via names and... it fixed the problem, but game i added twice was not there...

i will take a look later at the code handing this functionality.
